scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android
        script: flutter build apk --release
      - name: Build iOS
        script: |
          # نلغي أي محاولة لجلب الشهادات ونبني مباشرة
          flutter build ipa --release --no-codesign